Pa 156 python documentation
pactfi/pact-py-sdk pull request #6
Opened 2022-05-05 12:12 UTC by mark-pact

Developer documentation for the python script. This should have no change in functionality, only comments have been added to the code.

2022-05-24 13:48 UTC, Sernikjamnika approved these changes

2022-05-24 14:03 UTC, Sernikjamnika requested changes
Sorry, approved by misclick

2022-05-24 14:39 UTC, Sernikjamnika commented on pactsdk/transaction_group.py
> +"""
What do you think about removing this, since the class is well documented?

2022-06-09 14:41 UTC, tulustul commented
Moved to https://github.com/pactfi/pact-py-sdk/pull/7

2022-06-09 14:41 UTC, closed without merging